# Generated by Django 5.2.14 on 2026-05-24 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity Invoices'), ('CORPORATE_TRAVEL', 'Corporate Travel Logs')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of file contents for idempotency verification', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Ingestion'), ('PARSING', 'Parsing CSV File'), ('COMPLETED', 'Ingestion Completed'), ('FAILED', 'Ingestion Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactorReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='Broad classification, e.g., Fuel, Grid Electricity, Air Travel, Hotel', max_length=100)),
                ('activity_type', models.CharField(help_text='Specific activity, e.g., Diesel, Grid Electricity (US eGRID), Flight (Short-haul), Hotel room-night', max_length=150)),
                ('source_name', models.CharField(help_text='Regulatory source database, e.g. DEFRA 2023, EPA eGRID 2023, IPCC AR6', max_length=100)),
                ('factor_value', models.DecimalField(decimal_places=6, help_text='CO2e value per factor unit', max_digits=12)),
                ('unit', models.CharField(help_text='Unit of emission mapping, e.g., kg CO2e/liter, kg CO2e/kWh, kg CO2e/passenger-mile', max_length=50)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
            options={
                'ordering': ['category', 'activity_type', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField(help_text='Original cell values mapped as a key-value dictionary')),
                ('import_status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('VALIDATED', 'Validated (Success)'), ('FAILED_VALIDATION', 'Validation Failed'), ('NORMALIZED', 'Normalized')], default='UNPROCESSED', max_length=20)),
                ('errors', models.JSONField(blank=True, default=list, help_text='Array of parser or validator errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='esg_ingest.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='esg_ingest.tenant')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 (Direct)'), (2, 'Scope 2 (Indirect - Utilities)'), (3, 'Scope 3 (Indirect - Other/Travel)')])),
                ('category', models.CharField(help_text='e.g. Stationary Combustion, Purchased Electricity, Business Travel', max_length=100)),
                ('activity_type', models.CharField(help_text='e.g. Diesel Fuel, Purchased Electricity (MISO Grid), Air Travel - Short-haul', max_length=150)),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_quantity_co2e', models.DecimalField(decimal_places=6, help_text='Calculated greenhouse emissions in metric tonnes of CO2e (tCO2e)', max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('facility_or_plant', models.CharField(max_length=100)),
                ('review_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reasons', models.JSONField(blank=True, default=list, help_text='Array of warnings explaining why this row is suspicious')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked records cannot be edited or modified since they have been approved for audit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='esg_ingest.datasource')),
                ('factor_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='esg_ingest.emissionfactorreference')),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='esg_ingest.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='esg_ingest.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE', 'Created Record'), ('EDIT', 'Edited Fields'), ('APPROVE', 'Approved & Locked Record'), ('REJECT', 'Rejected Record')], max_length=20)),
                ('performed_by', models.CharField(default='System Ingestion', max_length=150)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, help_text="Before and After audit map, e.g. {'normalized_quantity_co2e': {'before': 10, 'after': 8.5}}", null=True)),
                ('comment', models.TextField(blank=True, help_text='Analyst explanation for why edits/overrides were executed', null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='esg_ingest.normalizedemissionrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='esg_ingest.tenant')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='esg_ingest.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('tenant', 'file_hash')},
        ),
    ]
